# Generated by Django 2.0.6 on 2018-09-26 20:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True)),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_source', to='api.Currency')),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchange_target', to='api.Currency')),
            ],
        ),
    ]
