# Generated by Django 2.0.6 on 2018-09-26 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='symbol',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
