sudo: required
dist: trusty

services:
- docker

env:
- TRAVIS_CI=True

install:
- docker-compose pull
- docker-compose build

script:
- docker-compose run -e TRAVIS_CI=True --no-deps app /venv/bin/python -m pytest