sudo: required
dist: trusty

services:
- docker

install:
- docker-compose pull
- docker-compose build

script:
- docker-compose up --build -d
- docker-compose exec app /venv/bin/python -m pytest
