version: '2'

services:
  db:
    environment:
      POSTGRES_DB: cc_dsk
      POSTGRES_USER: cc_dsk
      POSTGRES_PASSWORD: 4g5h453dfs32sd32
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  redis:
    restart: always
    image: redis:3.0
    expose:
      - "6379"
  app:
    environment:
      DATABASE_URL: postgres://cc_dsk:4g5h453dfs32sd32@db/cc_dsk
      REDIS_URL: redis://redis
      DJANGO_MANAGEPY_MIGRATE: 1
    build:
      context: .
      dockerfile: ./Dockerfile
    links:
      - db:db
      - redis:redis
    ports:
      - "8000:8000"