version: '2'

services:
  db:
    environment:
      POSTGRES_DB: cc_dsk
      POSTGRES_USER: cc_dsk
      POSTGRES_PASSWORD: 4g5h453dfs32sd32
    restart: always
    image: postgres:9.6
    expose:
      - "5432"
  app:
    environment:
      DATABASE_URL: postgres://cc_dsk:4g5h453dfs32sd32@db/cc_dsk
      DJANGO_MANAGEPY_MIGRATE: 1
    build:
      context: .
      dockerfile: ./Dockerfile
    depends_on:
      - db
    links:
      - db:db
    ports:
      - "8000:8000"